#=======================#
#      TeleportBow      #
#       By SyphiX       #
#=======================#

give_on_join: true
#You are able to choose if you want to give to everyone a TeleportBow on join
sound_on_shoot: "BLOCK_GLASS_BREAK"
#You are able to choose if you want to play sound whenever players shoot an arrow
teleport_to_entity: true
#You are able to choose if you want to teleport players to entity whenever they hit an entities with TeleportBow
teleport_to_block: true
#You are able to choose if you want to teleport players to block whenever they hit a block with TeleportBow
no_arrow_damage: false
#You are able to choose if you want to set arrow damage to 0
glowing_arrow: false
#You are able to choose if you want to set glowing on arrow
drop_on_death: false

bow:
  display_name: "<#0080ff>Teleport Bow"
  lore:
    - ""
    - "<aqua>By SyphiX"
  enchantment_particle: true
  unbreakable: true
  slot: 0

arrow:
  display_name: "<#0080ff>Arrow"
  custom_name: "<green>Arrow"
  # If you want to disable this feature, set it to ""
  lore:
    - ""
    - "<aqua>By SyphiX"
  slot: 9