#=======================#
#      TeleportBow      #
#       By SyphiX       #
#=======================#

# Note:
# Teleport items are referred to Teleport Bow and Teleport Arrow

# Give teleport items
give_on_join: true
# Should player teleport to arrow location if it hit an entity?
teleport_to_entity: true
# Should player teleport to arrow location if it hit a block?
teleport_to_block: true
# Prevent arrow damage on hit
no_arrow_damage: false
# Set glowing effect on arrow
glowing_arrow: false
# Drop teleport items on death
drop_on_death: false
# Allow TeleportBow to have infinity arrow
infinity_arrow: false
# Give teleport items when respawned
give_on_respawn: true

bow:
  display_name: "<#0080ff>Teleport Bow"
  lore:
    - ""
    - "<aqua>Jump between universe! Don't believe me? try and see!"
  enchantment_particle: true
  unbreakable: true
  slot: 0

arrow:
  display_name: "<#0080ff>Arrow"
  # Arrow Nameplate on launch
  custom_name:
    enabled: true
    name: "<green>Arrow"

  # summon particle on arrow hit
  hit_particle:
    on_hitting_entity:
      enabled: true
      name: "VILLAGER_HAPPY"
      radius: 1.0

    on_hitting_block:
      enabled: true
      name: "VILLAGER_HAPPY"
      radius: 1.0

  # summon particle on arrow shoot
  launch_particle:
    enabled: true
    name: "VILLAGER_HAPPY"

  # Play sound on arrow hit
  hit_sound:
    on_hitting_entity:
      enabled: true
      name: "ENTITY_ENDERMAN_TELEPORT"

    on_hitting_block:
      enabled: true
      name: "ENTITY_ENDERMAN_TELEPORT"

  # Play sound on arrow shoot
  launch_sound:
    enabled: true
    name: "ENTITY_PLAYER_LEVELUP"

  lore:
    - ""
    - "<aqua>The arrow of gods that's been used by Apollo itself."
  slot: 9