
#=======================#
#      TeleportBow      #
#      By SyphiX        #
#=======================#

give-on-join: true
#You are able to choose if you want to give to everyone a TeleportBow on join
sound-on-shoot: "BLOCK_GLASS_BREAK"
#You are able to choose if you want to play sound whenever players shoot an arrow
teleport-to-entity: true
#You are able to choose if you want to teleport players to entity whenever they hit an entities with TeleportBow
teleport-to-block: true
#You are able to choose if you want to teleport players to block whenever they hit a block with TeleportBow
no-arrow-damage: false
#You are able to choose if you want to set arrow damage to 0

teleport-bow:
  display-name: "<#0080ff>Teleport Bow"
  lore:
    - ""
    - "<aqua>By SyphiX"
  enchantment-particle: true
  unbreakable: true
  slot: 0

arrow:
  display-name: "<#0080ff>Arrow"
  lore:
    - ""
    - "<aqua>By SyphiX"
  slot: 9




